Repository usnistgov/WIPP-frontend, pull requests merged in 2020-01, with the labels that each got.

#139 feat: add pyramid visualizations
  src/app/app.component.html
  src/app/app.module.ts
  src/app/pyramid-visualization/pyramid-visualization-detail/pyramid-visualization-detail.component.css
  src/app/pyramid-visualization/pyramid-visualization-detail/pyramid-visualization-detail.component.html
  src/app/pyramid-visualization/pyramid-visualization-detail/pyramid-visualization-detail.component.spec.ts
  src/app/pyramid-visualization/pyramid-visualization-detail/pyramid-visualization-detail.component.ts
  src/app/pyramid-visualization/pyramid-visualization-help/pyramid-visualization-help.component.css
  src/app/pyramid-visualization/pyramid-visualization-help/pyramid-visualization-help.component.html
  src/app/pyramid-visualization/pyramid-visualization-help/pyramid-visualization-help.component.spec.ts
  src/app/pyramid-visualization/pyramid-visualization-help/pyramid-visualization-help.component.ts
  src/app/pyramid-visualization/pyramid-visualization-list/pyramid-visualization-list.component.css
  src/app/pyramid-visualization/pyramid-visualization-list/pyramid-visualization-list.component.html
  src/app/pyramid-visualization/pyramid-visualization-list/pyramid-visualization-list.component.spec.ts
  src/app/pyramid-visualization/pyramid-visualization-list/pyramid-visualization-list.component.ts
  src/app/pyramid-visualization/pyramid-visualization-new/pyramid-visualization-new.component.css
  src/app/pyramid-visualization/pyramid-visualization-new/pyramid-visualization-new.component.html
  src/app/pyramid-visualization/pyramid-visualization-new/pyramid-visualization-new.component.spec.ts
  src/app/pyramid-visualization/pyramid-visualization-new/pyramid-visualization-new.component.ts
  src/app/pyramid-visualization/pyramid-visualization-routing.module.ts
  src/app/pyramid-visualization/pyramid-visualization.module.ts
  src/app/pyramid-visualization/pyramid-visualization.service.spec.ts
  src/app/pyramid-visualization/pyramid-visualization.service.ts
  src/app/pyramid-visualization/visualization.ts
  src/app/pyramid/pyramid.service.ts
  src/assets/img/loading.svg
  src/styles.css
Labels: feature

#136 Feature/upload csv collection
  src/app/app.component.html
  src/app/csv-collection/csv-collection-detail/csv-collection-detail.component.css
  src/app/csv-collection/csv-collection-detail/csv-collection-detail.component.html
  src/app/csv-collection/csv-collection-list/csv-collection-list.component.html
  src/app/csv-collection/csv-collection-list/csv-collection-list.component.ts
  src/app/csv-collection/csv-collection-new/csv-collection-new.component.css
  src/app/csv-collection/csv-collection-new/csv-collection-new.component.html
  src/app/csv-collection/csv-collection-new/csv-collection-new.component.spec.ts
  src/app/csv-collection/csv-collection-new/csv-collection-new.component.ts
  src/app/csv-collection/csv-collection.module.ts
  src/app/csv-collection/csv-collection.service.ts
  src/app/csv-collection/csv-collection.ts
Labels: feature

#140 feat: update wdzt to 1.0.1 (new colormap filter)
  angular.json
  package-lock.json
  package.json
Labels: dependency-upgrade, feature

#142 feat: added link to catalog app
  README.md
  sample-config.json
  src/app/images-collection/images-collection-detail/images-collection-detail.component.html
  src/app/images-collection/images-collection-detail/images-collection-detail.component.ts
  src/app/images-collection/images-collection.ts
Labels: feature

#148 fix: avoid duplicated job dependencies during job creation
  src/app/workflow/workflow-detail/workflow-detail.component.ts
Labels: bug

#149 fix: default values from manifest for non-enum types in job form
  src/app/workflow/workflow-detail/workflow-detail.component.ts
Labels: bug

#147 feat: add catalog url management for deployment
  Jenkinsfile
  deploy/docker/config.json
  deploy/docker/entrypoint.sh
  deploy/kubernetes/frontend-deployment.yaml
Labels: feature

#145 chore: homogenize display of error message + rm css
  src/app/stitching-vector/stitching-vector-list/stitching-vector-list.component.ts
  src/app/stitching-vector/stitching-vector-new/stitching-vector-new.component.css
  src/app/stitching-vector/stitching-vector-new/stitching-vector-new.component.html
  src/app/stitching-vector/stitching-vector-new/stitching-vector-new.component.ts
Labels: enhancement

#144 Feature/upload CSV collection chunk
  src/app/csv-collection/csv-collection-detail/csv-collection-detail.component.css
  src/app/csv-collection/csv-collection-detail/csv-collection-detail.component.html
  src/app/csv-collection/csv-collection-detail/csv-collection-detail.component.ts
  src/app/csv-collection/csv-collection-list/csv-collection-list.component.ts
  src/app/csv-collection/csv-collection-new/csv-collection-new.component.html
  src/app/csv-collection/csv-collection-new/csv-collection-new.component.ts
  src/app/csv-collection/csv-collection.module.ts
  src/app/csv-collection/csv-collection.service.ts
  src/app/csv-collection/csv-collection.ts
  src/app/csv-collection/csv.ts
Labels: feature
