Repository usnistgov/WIPP-frontend, pull requests merged in 2020-02, with the labels that each got.

#153 Feature/copy of job in workflow
  src/app/csv-collection/csv-collection-detail/csv-collection-detail.component.ts
  src/app/csv-collection/csv-collection-list/csv-collection-list.component.ts
  src/app/csv-collection/csv-collection-template/csv-collection-template.component.ts
  src/app/csv-collection/csv-collection.service.ts
  src/app/csv-collection/csv-collection.ts
  src/app/csv-collection/csv.ts
  src/app/data-service.ts
  src/app/images-collection/image.ts
  src/app/images-collection/images-collection-detail/images-collection-detail.component.html
  src/app/images-collection/images-collection-detail/images-collection-detail.component.ts
  src/app/images-collection/images-collection-list/images-collection-list.component.ts
  src/app/images-collection/images-collection-template/images-collection-template.component.ts
  src/app/images-collection/images-collection.service.ts
  src/app/images-collection/images-collection.ts
  src/app/images-collection/metadata-file.ts
  src/app/notebook/notebook-detail/notebook-detail.component.ts
  src/app/notebook/notebook-list/notebook-list.component.ts
  src/app/notebook/notebook-template/notebook-template.component.ts
  src/app/notebook/notebook.service.ts
  src/app/notebook/notebook.ts
  src/app/pyramid-visualization/pyramid-visualization-detail/pyramid-visualization-detail.component.ts
  src/app/pyramid-visualization/pyramid-visualization-list/pyramid-visualization-list.component.ts
  src/app/pyramid-visualization/pyramid-visualization.service.ts
  src/app/pyramid-visualization/visualization.ts
  src/app/pyramid/pyramid-detail/pyramid-detail.component.ts
  src/app/pyramid/pyramid-list/pyramid-list.component.ts
  src/app/pyramid/pyramid-template/pyramid-template.component.ts
  src/app/pyramid/pyramid.service.ts
  src/app/pyramid/pyramid.ts
  src/app/stitching-vector/stitching-vector-detail/stitching-vector-detail.component.ts
  src/app/stitching-vector/stitching-vector-list/stitching-vector-list.component.ts
  src/app/stitching-vector/stitching-vector-template/stitching-vector-template.component.ts
  src/app/stitching-vector/stitching-vector.service.ts
  src/app/stitching-vector/stitching-vector.ts
  src/app/stitching-vector/timeSlice.ts
  src/app/tensorflow-model/tensorflow-model-detail/tensorflow-model-detail.component.ts
  src/app/tensorflow-model/tensorflow-model-list/tensorflow-model-list.component.ts
  src/app/tensorflow-model/tensorflow-model-template/tensorflow-model-template.component.ts
  src/app/tensorflow-model/tensorflow-model.service.ts
  src/app/tensorflow-model/tensorflow-model.ts
  src/app/workflow/widgets/search-widget/search-widget.component.ts
  src/app/workflow/workflow-detail/workflow-detail.component.html
  src/app/workflow/workflow-detail/workflow-detail.component.ts
Labels: feature

#155 feat: edit of workflow task
  src/app/workflow/workflow-detail/workflow-detail.component.css
  src/app/workflow/workflow-detail/workflow-detail.component.html
  src/app/workflow/workflow-detail/workflow-detail.component.ts
  src/app/workflow/workflow.service.ts
Labels: feature

#154 feat: deletion of CSV files
  src/app/csv-collection/csv-collection-detail/csv-collection-detail.component.html
  src/app/csv-collection/csv-collection-detail/csv-collection-detail.component.ts
  src/app/csv-collection/csv-collection.service.ts
  src/app/csv-collection/csv-collection.ts
Labels: feature

#157 fix: sort by size in imagesCollection details page
  src/app/images-collection/images-collection-detail/images-collection-detail.component.html
  src/app/images-collection/images-collection-detail/images-collection-detail.component.ts
Labels: bug

#159 feat: add help links to menu bar
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.ts
Labels: feature

#160 fix: disable addFiles button if csvCollection.sourceJob
  src/app/csv-collection/csv-collection-detail/csv-collection-detail.component.html
Labels: enhancement

#162 Feature/remove button to add files CSV collection
  src/app/csv-collection/csv-collection-detail/csv-collection-detail.component.html
Labels: enhancement

#163 fix: handling of pyramids as inputs/outputs, tensorboardLogs as outputs
  src/app/workflow/workflow-detail/workflow-detail.component.ts
Labels: bug

#164 fix: handle CSV page changed
  src/app/csv-collection/csv-collection-detail/csv-collection-detail.component.html
  src/app/csv-collection/csv-collection-detail/csv-collection-detail.component.ts
Labels: bug

#165 fix: jobModel for inputs without widget and string array
  src/app/workflow/workflow-detail/workflow-detail.component.ts
Labels: bug

#166 fix: add brackets to name of previous inputs when copy/edit a task
  src/app/workflow/workflow-detail/workflow-detail.component.ts
Labels: enhancement

#167 feat: link to Swagger Ui disabled in production
  src/app/app.component.html
  src/app/app.component.ts
Labels: enhancement

#168 fix: closing new sv modal when saving
  src/app/stitching-vector/stitching-vector-list/stitching-vector-list.component.ts
Labels: enhancement

#169 fix: rm plot link from navbar
  src/app/app.component.html
  src/app/app.component.ts
Labels: enhancement
